NAS-4284 documentation update
gooddata/gooddata-python-sdk pull request #141
Opened 2022-08-24 13:51 UTC by hkad98

2022-08-24 13:51 UTC, gdgate commented
Build succeeded (check pipeline).

2022-08-24 15:01 UTC, jaceksan requested changes

2022-08-24 15:12 UTC, hkad98 commented on gooddata-sdk/docs/services/catalog-workspace-content.rst
> +    # TODO
Nope. I forgot. I will fix it. Thanks.

2022-08-25 09:10 UTC, gdgate commented
Build succeeded (check pipeline).

2022-08-25 09:10 UTC, hkad98 commented on gooddata-sdk/docs/services/catalog-data-source.rst
> +* ``store_declarative_pdm(data_source_id: str, layout_root_path: Path = Path.cwd())``
Fixed.

2022-08-25 09:10 UTC, hkad98 commented on gooddata-sdk/docs/services/catalog-data-source.rst
> +
Added.

2022-08-25 09:10 UTC, hkad98 commented on gooddata-sdk/docs/services/catalog-data-source.rst
> +    Tests connection to declarative data sources. We can specify an optional path to credentials.
Done.

2022-08-26 06:11 UTC, jaceksan approved these changes

2022-08-26 06:17 UTC, gdgate commented
Build succeeded (check pipeline).

2022-08-26 06:49 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR141

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2022-08-26 06:49 UTC, merged

2022-08-26 06:49 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/127/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul-el7/127/ : FAILURE in 53s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/129/ : SUCCESS in 20s