PSDK-28 unified api client
gooddata/gooddata-python-sdk pull request #155
Opened 2022-09-22 12:33 UTC by hkad98

2022-09-22 12:33 UTC, gdgate commented
Build succeeded (check pipeline).

2022-09-22 14:45 UTC, gdgate commented
Build succeeded (check pipeline).

2022-09-22 18:00 UTC, gdgate commented
Build succeeded (check pipeline).

2022-10-03 09:27 UTC, pcerny requested changes

2022-10-03 09:27 UTC, pcerny commented on Makefile
> +download:
Generate also exporter endpoints to the unified api client. See https://staging.anywhere.gooddata.com/apidocs/?urls.primaryName=Export%20(v1).

2022-10-03 09:27 UTC, pcerny commented on scripts/generate_client.sh
>      GD_API_URI_PATH="${GD_SCHEMA_URL}/api/${API_VERSION}/schemas/afm"
Improve usage help. Add there that `gooddata-api-client` as supported option.

2022-10-03 09:27 UTC, pcerny commented on gooddata-api-client/LICENSE.txt
> +../OSS LICENSES/LICENSE (gooddata-api-client).txt
It looks like invalid symlink. I do not see `OSS LICENSES/LICENSE (gooddata-api-client).txt` being part of PR.

2022-10-04 13:26 UTC, gdgate commented
Build succeeded (check pipeline).

2022-10-04 13:27 UTC, gdgate commented
Build succeeded (check pipeline).

2022-10-04 14:02 UTC, pcerny approved these changes

2022-10-04 14:32 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR155

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2022-10-04 14:32 UTC, merged