Improvements to prism code highlighting of Python
gooddata/gooddata-python-sdk pull request #236
Opened 2023-03-13 10:23 UTC by basta

2023-03-13 10:24 UTC, gdgate commented
Build succeeded (check pipeline).

2023-03-14 14:07 UTC, Mara3l requested changes

2023-03-14 14:07 UTC, Mara3l commented on docs/static/js/prism-python-plugin.js
> +            pattern: /\b(?:os|time|numpy|Path)\b/,
Add also `sdk.` and `GoodDataSDK.`

2023-03-15 08:28 UTC, Mara3l commented on docs/static/js/prism-python-plugin.js
> +            pattern: /\b(?:os|time|numpy|Path)\b/,
Also, please make it highlight Java(Type)Script and bash as well. Thanks!

2023-03-17 06:43 UTC, hkad98 commented
There are a lot of commits, please, squash them into one commit.

2023-03-17 13:02 UTC, gdgate commented
Build succeeded (check pipeline).

2023-03-17 13:09 UTC, gdgate commented
Build succeeded (check pipeline).

2023-03-17 13:30 UTC, Mara3l approved these changes

2023-03-17 13:43 UTC, hkad98 approved these changes

2023-03-17 14:16 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR236

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2023-03-17 14:16 UTC, merged