CAL-788: Support UserDataFilter
gooddata/gooddata-python-sdk pull request #263
Opened 2023-04-06 22:38 UTC by mcermak

2023-04-06 22:38 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-06 23:32 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 08:04 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 09:20 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 10:52 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 12:09 UTC, pcerny requested changes
gooddata-sdk documentation is generated from https://github.com/gooddata/gooddata-python-sdk/tree/master/docs/content/en/docs. Please extend also this part or create follow-up. Agree on proper steps with @hkad98 and @Mara3l .

2023-04-13 12:09 UTC, pcerny commented on gooddata-sdk/gooddata_sdk/catalog/workspace/service.py
> +from gooddata_sdk.catalog.workspace.entity_model.user_data_filter import (
Use imports from `gooddata_sdk` package.

2023-04-13 12:09 UTC, pcerny commented on gooddata-sdk/tests/catalog/test_catalog_workspace.py
> +from gooddata_sdk.catalog.workspace.entity_model.user_data_filter import CatalogUserDataFilter
Use imports from `gooddata_sdk` package.

2023-04-13 13:04 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 13:08 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 14:36 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-13 14:42 UTC, mcermak commented on gooddata-sdk/gooddata_sdk/catalog/workspace/entity_model/user_data_filter.py
> +    data: CatalogEntityIdentifier
This approach is already used in use and userGroup, butt in general I agree that it is strange. I will try to find a way how to avoid it.

2023-04-13 16:56 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-14 07:16 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-14 07:42 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-14 08:07 UTC, gdgate commented
Build succeeded (check pipeline).

2023-04-14 08:18 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR263

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2023-04-14 08:19 UTC, merged

2023-04-14 08:19 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/87/ : FAILURE in 1m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/237/ : SUCCESS in 1m 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/240/ : SUCCESS in 14s