Add support for dashboard permissions 'share with everyone'
gooddata/gooddata-python-sdk pull request #392
Opened 2023-10-23 08:09 UTC by vojtechtoman

- introduce a workaround in `model_utils.moustache` to better support `oneOf` with the currently used version of openapi-generator
- regenerate api-client
- add support for the `allWorkspaceUsers` rule and fix some of the existing code to work with the `oneOf` fix/workaround

2023-10-23 08:09 UTC, gdgate commented
Build succeeded (check pipeline).

2023-10-24 13:33 UTC, gdgate commented
Build succeeded (check pipeline).

2023-10-24 14:10 UTC, pcerny requested changes

2023-10-24 14:18 UTC, gdgate commented
Build succeeded (check pipeline).

2023-10-24 14:22 UTC, vojtechtoman commented on gooddata-sdk/gooddata_sdk/catalog/permission/declarative_model/manage_dashboard_permissions.py
> +class CatalogPermissionsAssignment(Base):
`CatalogPermissionsAssignment` is actually intended because it allows either `assignee_identifier` or `assignee_rule`.

2023-10-24 16:26 UTC, gdgate commented
Build succeeded (check pipeline).

2023-10-25 06:57 UTC, gdgate commented
Build succeeded (check pipeline).

2023-10-25 08:30 UTC, pcerny approved these changes

2023-10-25 08:32 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR392

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2023-10-25 08:33 UTC, merged

2023-10-25 08:33 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/208/ : FAILURE in 1m 17s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/358/ : SUCCESS in 1m 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/361/ : SUCCESS in 9s