RELATED: PSDK-173 add support for user management APIs
gooddata/gooddata-python-sdk pull request #589
Opened 2024-03-09 16:30 UTC by hkad98

2024-03-09 16:30 UTC, gdgate commented
Build succeeded (check pipeline).

2024-03-10 08:56 UTC, jaceksan requested changes

2024-03-10 08:56 UTC, jaceksan commented on docker-compose.yaml
> +    image: 020413372491.dkr.ecr.us-east-1.amazonaws.com/nas/gooddata-cn-ce:stable
The comment above talks about the latest tag, but stable tag is used.
Please, explain shortly why we use stable.

2024-03-10 09:36 UTC, gdgate commented
Build succeeded (check pipeline).

2024-03-10 11:00 UTC, jaceksan approved these changes

2024-03-10 16:28 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR589

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2024-03-10 16:28 UTC, merged

2024-03-10 16:28 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/336/ : FAILURE in 1m 05s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/486/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/490/ : SUCCESS in 6s