feature(gooddata-sdk): support date filters for get elements
gooddata/gooddata-python-sdk pull request #602
Opened 2024-03-20 13:48 UTC by mcermak

JIRA: LX-161

2024-03-20 13:48 UTC, gdgate commented
Build succeeded (check pipeline).

2024-03-20 13:58 UTC, gdgate commented
Build succeeded (check pipeline).

2024-03-21 08:24 UTC, pcerny requested changes

2024-03-21 08:24 UTC, pcerny commented on gooddata-sdk/gooddata_sdk/catalog/workspace/content_service.py
> +            depends_on (Optional[List[CatalogDependsOnItem]]):
Typo. `CatalogDependsOnItem` -> `DependsOnItem`

2024-03-21 08:32 UTC, gdgate commented
Build succeeded (check pipeline).

2024-03-21 08:46 UTC, pcerny approved these changes

2024-03-21 08:48 UTC, merged

2024-03-21 08:48 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/343/ : FAILURE in 1m 34s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/493/ : SUCCESS in 1m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/497/ : SUCCESS in 6s