Doing science
gooddata/gooddata-python-sdk pull request #69
Opened 2022-01-29 11:51 UTC by SubTachyon

2022-01-29 11:51 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 13:50 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 13:56 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 14:07 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 14:14 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 15:40 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 16:25 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 16:31 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-29 16:32 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-30 13:51 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-30 14:05 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-30 14:11 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 09:12 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 09:13 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 09:39 UTC, pcerny requested changes

2022-01-31 09:39 UTC, pcerny commented on gooddata-fdw/docs/connecting_to_postgresql.rst
> +Import GoodData Objects into PostgreSQL Schema
This section should be in `Foreign tables` chapter.

2022-01-31 10:33 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 10:40 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 10:45 UTC, pcerny approved these changes

2022-01-31 11:21 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 11:21 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 12:06 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 12:06 UTC, gdgate commented
Build succeeded (check pipeline).

2022-01-31 12:20 UTC, pcerny approved these changes

2022-01-31 12:21 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR69

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2022-01-31 12:22 UTC, merged

2022-01-31 12:22 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/62/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul-el7/62/ : FAILURE in 1m 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/62/ : SUCCESS in 20s